config/routes.rb
Rails.application.routes.draw do
  root "client#index"
  get "/google_login" => "auth#google_login"
  get "/logout" => "auth#logout"
  get "/store/:id" => "client#store_page", as: "store"
  get "/category/:id" => "client#category_page", as: "category"
  get "/offer/:id" => "client#offer_page", as: "offer"
  get "/offer/action/:id" => "client#offer_show", as: "offer_show"
  get "/categories" => "client#categories", as: "categories"
  get "/offers" => "client#offers", as: "offers"
  get "/stores" => "client#stores", as: "stores"
  get "/invite/:ref_code" => "client#invite"
  get "/admin/dashboard" => "admin/dashboard#index"
  get "/admin" => "admin/login#new"
  post "/admin" => "admin/login#login"
  delete "/admin/logout" => "admin/login#logout"

  namespace :admin do
    post "/payout_user/:id", to: "admin#payout", as: "payout_user"
    resources :payouts
    resources :users
    resources :coupon_categories do
      resources :coupon_sub_categories
    end
    resources :coupon_stores
    resources :coupon_offers
    resources :redeem_histories
    resources :notifications
  end
  mount API::Base => "/"
end

app/models/coupon_category.rb
class CouponCategory < ApplicationRecord
  has_many :coupon_stores, dependent: :destroy
  has_many :coupon_sub_categories, dependent: :destroy
  has_many :coupon_offers, dependent: :destroy

  scope :active, -> { where(:status => "active").order(created_at: :desc) }
end

app/controllers/admin/coupon_categories_controller.rb
class Admin::CouponCategoriesController < Admin::AdminController
  before_action :authenticate_user!
  layout "admin"

  def index
    @categories = CouponCategory.all.paginate(page: params[:page], per_page: 20).order(created_at: :desc)
  end

  def new
    @category = CouponCategory.new
  end

  def create
    @category = CouponCategory.new(category_params)
    if @category.save
      redirect_to admin_coupon_categories_path, notice: "Category was successfully created."
    else
      render :new
    end
  end

  def edit
    @category = CouponCategory.find(params[:id])
  end

  def update
    @category = CouponCategory.find(params[:id])
    if @category.update(category_params)
      redirect_to admin_coupon_categories_path, notice: "Category was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @category = CouponCategory.find(params[:id])
    @category.destroy
    redirect_to admin_coupon_categories_path, notice: "Category was successfully destroyed."
  end

  private

  def category_params
    params.require(:coupon_category).permit(:name, :img_url, :status)
  end
end

app/views/admin/coupon_categories/edit.html.erb
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <h2 class="page-header">New Category</h2>
      </div>
      <div class="col-lg-6">
        <%= form_with(model: @category,url: admin_coupon_category_path) do |form| %>
          <div class="form-group">
            <%= form.label :name %>
            <%= form.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= form.label :img_url %>
            <%= form.text_field :img_url, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= form.label :status %>
            <%= form.select :status, options_for_select([['Active', 'active'], ['Inactive', 'inactive']], @category.status), {}, class: 'form-control' %>
          </div>
          <div class="actions">
            <%= form.submit 'Save', class: 'btn btn-primary' %>
            <%= link_to 'Cancel', admin_coupon_categories_path, class: 'btn btn-default' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/coupon_categories/index.html.erb
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <p id="notice" style="color:orange;"><%= notice %></p>
      <div class="col-lg-12">
        <h2 class="page-header" style="margin: 10px 0 15px !important;">Listing Coupon Categories</h2>
      </div>
      <div class="col-lg-12 text-right">
        <%= link_to 'New Category', new_admin_coupon_category_path, class: 'btn btn-primary', style: 'margin-bottom: 10px;' %>
      </div>
      <% if @categories.present? %>
        <table class="table table-responsive table-bordered">
          <thead>
            <tr>
              <th>Id</th>
              <th>Coupon Name</th>
              <th>Coupon Image</th>
              <th>Status</th>
              <th>Date Time</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <% @categories.each do |category| %>
              <tr>
                <td><%= category.id %></td>
                <td><%= category.name %></td>
                <td><img style="width:40px;" src="<%=category.try(:img_url)%>" onerror="this.onerror=null;this.src='https://cdn.pixabay.com/photo/2014/03/24/17/21/wrong-295503_640.png';" /></td>
                <td>
                  <% if category.status == "active" %>
                    <img style="width:20px;" src="https://cdn.pixabay.com/photo/2012/04/24/12/40/ticks-39830_960_720.png" />
                  <% else %>
                    <img style="width:20px;" src="https://cdn.pixabay.com/photo/2014/03/24/17/21/wrong-295503_640.png" />
                  <% end %>
                </td>
                <td><%= category.created_at.strftime("%d/%m/%y %I:%M %p") %></td>
                <td>
                  <div style="display:flex;gap:5px;">
                    <%= link_to 'Sub categories', admin_coupon_category_coupon_sub_categories_path(category),class: 'btn btn-default btn-sm' %>
                    <%= link_to 'Edit', edit_admin_coupon_category_path(category),class: 'btn btn-primary btn-sm' %>
                    <%= button_to 'Delete', admin_coupon_category_path(category), method: :delete,class: 'btn btn-danger btn-sm' %>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= will_paginate @categories %>
      <% else %>
        <h1 class="not-found">No Coupon Category Found</h1>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/coupon_categories/new.html.erb
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <h2 class="page-header">New Category</h2>
      </div>
      <div class="col-lg-6">
        <%= form_with(model: @category,url: admin_coupon_categories_path) do |form| %>
          <div class="form-group">
            <%= form.label :name %>
            <%= form.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= form.label :img_url %>
            <%= form.text_field :img_url, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= form.label :status %>
            <%= form.select :status, options_for_select([['Active', 'active'], ['Inactive', 'inactive']], @category.status), {}, class: 'form-control' %>
          </div>
          <div class="actions">
            <%= form.submit 'Save', class: 'btn btn-primary' %>
            <%= link_to 'Cancel', admin_coupon_categories_path, class: 'btn btn-default' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>